// ==========================================
// FILE: src/utils/generateStoreReport.js
// ==========================================

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
} from "docx";

import {
  saveAs,
} from "file-saver";

export async function generateStoreReport({

  storeName,

  storeDomain,

  stats,

  products,

  issues,
}) {

  // ======================================
  // PRODUCT TABLE ROWS
  // ======================================

  const productRows = [

    new TableRow({

      children: [

        new TableCell({

          children: [
            new Paragraph("Product"),
          ],
        }),

        new TableCell({

          children: [
            new Paragraph("Score"),
          ],
        }),

        new TableCell({

          children: [
            new Paragraph("Classification"),
          ],
        }),

        new TableCell({

          children: [
            new Paragraph("Issues"),
          ],
        }),
      ],
    }),

    ...products.map(
      (product) => {

        const issueText =
          product.aiProblems
            ?.length > 0
            ? product.aiProblems
                .slice(0, 3)
                .join(", ")
            : "No major issues";

        return new TableRow({

          children: [

            new TableCell({

              children: [

                new Paragraph(
                  product.title ||
                  "Untitled"
                ),
              ],
            }),

            new TableCell({

              children: [

                new Paragraph(
                  String(
                    product.overallScore ||
                    0
                  )
                ),
              ],
            }),

            new TableCell({

              children: [

                new Paragraph(
                  product.classification ||
                  "Average"
                ),
              ],
            }),

            new TableCell({

              children: [

                new Paragraph(
                  issueText
                ),
              ],
            }),
          ],
        });
      }
    ),
  ];

  // ======================================
  // ISSUE PARAGRAPHS
  // ======================================

  const issueParagraphs =
    issues.map(
      (issue) =>

        new Paragraph({

          spacing: {
            after: 180,
          },

          children: [

            new TextRun({

              text: `• ${issue.title}: `,

              bold: true,
            }),

            new TextRun({
              text:
                issue.description,
            }),
          ],
        })
    );

  // ======================================
  // DOCUMENT
  // ======================================

  const doc =
    new Document({

      sections: [

        {
          children: [

            // ============================
            // TITLE
            // ============================

            new Paragraph({

              heading:
                HeadingLevel.TITLE,

              alignment:
                AlignmentType.CENTER,

              spacing: {
                after: 400,
              },

              children: [

                new TextRun({

                  text:
                    "AI Store Audit Report",

                  bold: true,

                  size: 36,
                }),
              ],
            }),

            // ============================
            // STORE INFO
            // ============================

            new Paragraph({

              spacing: {
                after: 200,
              },

              children: [

                new TextRun({

                  text:
                    "Store Name: ",

                  bold: true,
                }),

                new TextRun({
                  text: storeName,
                }),
              ],
            }),

            new Paragraph({

              spacing: {
                after: 200,
              },

              children: [

                new TextRun({

                  text:
                    "Store Domain: ",

                  bold: true,
                }),

                new TextRun({
                  text: storeDomain,
                }),
              ],
            }),

            new Paragraph({

              spacing: {
                after: 500,
              },

              children: [

                new TextRun({

                  text:
                    "Generated By Kasparo AI Commerce Intelligence",

                  italics: true,
                }),
              ],
            }),

            // ============================
            // OVERALL SCORES
            // ============================

            new Paragraph({

              heading:
                HeadingLevel.HEADING_1,

              spacing: {
                after: 300,
              },

              text:
                "Store AI Scores",
            }),

            new Paragraph({

              children: [

                new TextRun({

                  text:
                    "AI Discoverability: ",

                  bold: true,
                }),

                new TextRun({

                  text: `${stats.discoverability}/100`,
                }),
              ],
            }),

            new Paragraph({

              children: [

                new TextRun({

                  text:
                    "Product Clarity: ",

                  bold: true,
                }),

                new TextRun({

                  text: `${stats.clarity}/100`,
                }),
              ],
            }),

            new Paragraph({

              children: [

                new TextRun({

                  text:
                    "Trust Signals: ",

                  bold: true,
                }),

                new TextRun({

                  text: `${stats.trust}/100`,
                }),
              ],
            }),

            new Paragraph({

              spacing: {
                after: 500,
              },

              children: [

                new TextRun({

                  text:
                    "Conversion Readiness: ",

                  bold: true,
                }),

                new TextRun({

                  text: `${stats.conversion}/100`,
                }),
              ],
            }),

            // ============================
            // ISSUES
            // ============================

            new Paragraph({

              heading:
                HeadingLevel.HEADING_1,

              spacing: {
                after: 300,
              },

              text:
                "Critical AI Issues",
            }),

            ...issueParagraphs,

            // ============================
            // PRODUCT TABLE
            // ============================

            new Paragraph({

              heading:
                HeadingLevel.HEADING_1,

              spacing: {
                before: 400,
                after: 300,
              },

              text:
                "Product Analysis",
            }),

            new Table({

              width: {
                size: 100,
                type:
                  WidthType.PERCENTAGE,
              },

              rows:
                productRows,
            }),

            // ============================
            // FOOTER
            // ============================

            new Paragraph({

              spacing: {
                before: 600,
              },

              alignment:
                AlignmentType.CENTER,

              children: [

                new TextRun({

                  text:
                    "Generated using Kasparo AI Optimization Engine",

                  italics: true,

                  color:
                    "666666",
                }),
              ],
            }),
          ],
        },
      ],
    });

  // ======================================
  // EXPORT DOCX
  // ======================================

  const blob =
    await Packer.toBlob(doc);

  saveAs(
    blob,

    `${storeName
      .replace(/\s/g, "_")}_AI_Report.docx`
  );
}